name: gql_rsocket_link
description: GQL Terminating Link to execute requests via RSocket using JSON.
version: 0.0.0
homepage: https://github.com/amondnet/gql_rsocket_link

environment:
  sdk: '>=2.16.1 <3.0.0'


dependencies:
  gql: ^0.13.0
  gql_exec: ^0.4.0
  gql_link: ^0.4.2
  meta: ^1.3.0
  rsocket:
  graphql:
dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
  test: ^1.16.0
